name: PSRule-ADO

pool:
  vmImage: "ubuntu-latest"

variables:
  # Set to your variable group containing variables
  - group: "azdo-psrule-run"

schedules:
  - cron: "0 6 * * *"
    displayName: Run every day at 6am
    branches:
      include:
        - "*"

stages:
  - stage: Run
    displayName: Run
    jobs:
      - job: Run
        displayName: Run PSRule.Rules.AzureDevOps
        steps:
          - checkout: self
            clean: true
          - task: PowerShell@2
            displayName: Install PowerShell Modules
            inputs:
              targetType: "inline"
              script: |
                Install-Module -Name PSRule.Monitor -Scope CurrentUser -Force
                Install-Module -Name PSRule.Rules.AzureDevOps -Scope CurrentUser -Force

          - task: PowerShell@2
            displayName: Create temporary output directory
            inputs:
              targetType: "inline"
              script: |
                New-Item -Path $(Build.SourcesDirectory) -Name Temp -ItemType Directory -Force

          - task: PowerShell@2
            displayName: Run PSRule
            inputs:
              targetType: "inline"
              errorActionPreference: continue
              script: |
                Import-Module PSRule.Monitor
                Connect-AzDevOps -Organization '$(AZDO-ORGANIZATION)' -PAT "$(AZDO-PAT)"
                # Export-AzDevOpsOrganizationRuleData -OutputPath .\Temp -ErrorAction Continue

                # Export-AzDevOpsRuleData -Project "ssc-set" -OutputPath .\Temp

                md $(Build.SourcesDirectory)\Temp\ssc-sep
                md $(Build.SourcesDirectory)\Temp\pmo-deg
                md $(Build.SourcesDirectory)\Temp\pmo-gdh
                md $(Build.SourcesDirectory)\Temp\ssc-sde
                md $(Build.SourcesDirectory)\Temp\ssc-vdi
                md $(Build.SourcesDirectory)\Temp\pmo-nza
                md $(Build.SourcesDirectory)\Temp\ssc-mss
                md $(Build.SourcesDirectory)\Temp\ssc-hlz
                md $(Build.SourcesDirectory)\Temp\mgt-nps
                md $(Build.SourcesDirectory)\Temp\pmo-dct
                md $(Build.SourcesDirectory)\Temp\ssc-plz
                md $(Build.SourcesDirectory)\Temp\ssc-obp
                md $(Build.SourcesDirectory)\Temp\pmo-uwb
                md $(Build.SourcesDirectory)\Temp\ssc-tlz
                md $(Build.SourcesDirectory)\Temp\ssc-mlz
                md $(Build.SourcesDirectory)\Temp\ssc-sst
                md $(Build.SourcesDirectory)\Temp\pmo-ssc
                md $(Build.SourcesDirectory)\Temp\ssc-set
                md $(Build.SourcesDirectory)\Temp\ssc-alz
                md $(Build.SourcesDirectory)\Temp\ssc-aia
                md $(Build.SourcesDirectory)\Temp\plt-sep
                md $(Build.SourcesDirectory)\Temp\ssc-adi
                md $(Build.SourcesDirectory)\Temp\plt-exp
                md $(Build.SourcesDirectory)\Temp\pmo-uwv
                md $(Build.SourcesDirectory)\Temp\ssc-dac
                md $(Build.SourcesDirectory)\Temp\ssc-mco

                Export-AzDevOpsRuleData -Project "ssc-sep" -OutputPath .\Temp\ssc-sep
                Export-AzDevOpsRuleData -Project "pmo-deg" -OutputPath .\Temp\pmo-deg
                Export-AzDevOpsRuleData -Project "pmo-gdh" -OutputPath .\Temp\pmo-gdh
                Export-AzDevOpsRuleData -Project "ssc-sde" -OutputPath .\Temp\ssc-sde
                Export-AzDevOpsRuleData -Project "ssc-vdi" -OutputPath .\Temp\ssc-vdi
                Export-AzDevOpsRuleData -Project "pmo-nza" -OutputPath .\Temp\pmo-nza
                Export-AzDevOpsRuleData -Project "ssc-mss" -OutputPath .\Temp\ssc-mss
                Export-AzDevOpsRuleData -Project "ssc-hlz" -OutputPath .\Temp\ssc-hlz
                Export-AzDevOpsRuleData -Project "mgt-nps" -OutputPath .\Temp\mgt-nps
                Export-AzDevOpsRuleData -Project "pmo-dct" -OutputPath .\Temp\pmo-dct
                Export-AzDevOpsRuleData -Project "ssc-plz" -OutputPath .\Temp\ssc-plz
                Export-AzDevOpsRuleData -Project "ssc-obp" -OutputPath .\Temp\ssc-obp
                Export-AzDevOpsRuleData -Project "pmo-uwb" -OutputPath .\Temp\pmo-uwb
                Export-AzDevOpsRuleData -Project "ssc-tlz" -OutputPath .\Temp\ssc-tlz
                Export-AzDevOpsRuleData -Project "ssc-mlz" -OutputPath .\Temp\ssc-mlz
                Export-AzDevOpsRuleData -Project "ssc-sst" -OutputPath .\Temp\ssc-sst
                Export-AzDevOpsRuleData -Project "pmo-ssc" -OutputPath .\Temp\pmo-ssc
                Export-AzDevOpsRuleData -Project "ssc-set" -OutputPath .\Temp\ssc-set
                Export-AzDevOpsRuleData -Project "ssc-alz" -OutputPath .\Temp\ssc-alz
                Export-AzDevOpsRuleData -Project "ssc-aia" -OutputPath .\Temp\ssc-aia
                Export-AzDevOpsRuleData -Project "plt-sep" -OutputPath .\Temp\plt-sep
                Export-AzDevOpsRuleData -Project "ssc-adi" -OutputPath .\Temp\ssc-adi
                Export-AzDevOpsRuleData -Project "plt-exp" -OutputPath .\Temp\plt-exp
                Export-AzDevOpsRuleData -Project "pmo-uwv" -OutputPath .\Temp\pmo-uwv
                Export-AzDevOpsRuleData -Project "ssc-dac" -OutputPath .\Temp\ssc-dac
                Export-AzDevOpsRuleData -Project "ssc-mco" -OutputPath .\Temp\ssc-mco

                $result = Invoke-PSRule `
                  -Module PSRule.Rules.AzureDevOps,PSRule.Monitor `
                  -InputPath '$(Build.SourcesDirectory)/Temp/' `
                  -Format Detect `
                  -Culture en
                $result | Send-PSRuleMonitorRecord -WorkspaceId '$(logAnalyticsWorkspaceId)' -SharedKey '$(logAnalyticsSharedKey)' -LogName PSRule
            env:
              PSRULE_CONVENTION_INCLUDE: "Monitor.LogAnalytics.Import"
